server:
  port: 8060
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: service-seed-project
  profiles:
    active: prod
  servlet:
    multipart:
      # 启用文件上传
      enabled: true
      # 最大文件大小
      max-file-size: 10MB
      # 最大请求大小
      max-request-size: 100MB
      # 文件大小阈值
      file-size-threshold: 0
      # 临时文件位置
      location: ${java.io.tmpdir}

# 文件上传配置
file:
  upload:
    # 上传目录
    path: ${user.dir}/uploads
    # 允许的文件类型
    allowed-types: .jpg,.jpeg,.png,.gif,.bmp,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.zip,.rar
    # 最大文件大小（字节）
    max-size: 10485760
    # 一次最多上传文件数量
    max-count: 10


mybatis-plus:
  configuration:
    # 开启下划线字段（如 merchant_name）自动转换为驼峰字段（merchantName）
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2.xml
