server:
  port: 8060
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: SpringBootServiceSeedProject
  profiles:
    active: dev


mybatis-plus:
  configuration:
    # 开启下划线字段（如 merchant_name）自动转换为驼峰字段（merchantName）
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2.xml
