spring:
  datasource:
    # druid相关配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      master:
        url: jdbc:mysql://106.15.7.132:3306/master?useUnicode=true&characterEncoding=utf-8&connectTimeout=15000&socketTimeout=15000
        username: master
        password: "zhaoyudong@1994"
        enabled: true
      log:
        url: jdbc:mysql://106.15.7.132:3306/log?useUnicode=true&characterEncoding=utf-8&connectTimeout=15000&socketTimeout=15000
        username: log
        password: "zhaoyudong@1994"
        enabled: true
      # 初始连接数
      initialSize: 10
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  redis:
    host: 127.0.0.1  # 或 localhost
    port: 6379       # 默认端口
    database: 0      # 可选，默认是0

# xxl-job 定时任务配置
xxl:
  job:
    admin:
      # 多个地址使用,分割
      addresses: http://106.15.7.132:8061/xxl-job-admin
      accessToken: default_token
    executor:
      appname: xxl-job-executor-${spring.application.name}
      address:
      ip:
      port: 9999  #执行器端口
      logpath: ./logs/xxl-job/jobhandler
      logretentiondays: 30
